# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: system_metrics.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'system_metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14system_metrics.proto\x12\rsystemmetrics\"\x9c\x01\n\x0eMetricsRequest\x12\x11\n\tcpu_usage\x18\x01 \x01(\t\x12\x11\n\tcpu_times\x18\x02 \x01(\t\x12\x15\n\rcpu_frequency\x18\x03 \x01(\t\x12\x11\n\ttotal_ram\x18\x04 \x01(\t\x12\x10\n\x08used_ram\x18\x05 \x01(\t\x12\x15\n\ravailable_ram\x18\x06 \x01(\t\x12\x11\n\tram_usage\x18\x07 \x01(\t\"\"\n\x0fMetricsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2]\n\rSystemMetrics\x12L\n\x0bSendMetrics\x12\x1d.systemmetrics.MetricsRequest\x1a\x1e.systemmetrics.MetricsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICSREQUEST']._serialized_start=40
  _globals['_METRICSREQUEST']._serialized_end=196
  _globals['_METRICSRESPONSE']._serialized_start=198
  _globals['_METRICSRESPONSE']._serialized_end=232
  _globals['_SYSTEMMETRICS']._serialized_start=234
  _globals['_SYSTEMMETRICS']._serialized_end=327
# @@protoc_insertion_point(module_scope)
